// @crafted-by: Sahil Sheikh | IG: @sahil_sheikh78 | Unauthorized use prohibited
"use client"; import { motion } from"framer-motion"; const galleryImages = [ { url:"https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=800", title:"Luxury Living" }, { url:"https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=800", title:"Healing Spaces" }, { url:"https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800", title:"Grand Lobbies" }, { url:"https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800", title:"Modern Workspaces" }, { url:"https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=800", title:"Minimalist Suites" }, { url:"https://images.unsplash.com/photo-1503708928676-1cb796a0891e?q=80&w=800", title:"Technical Perfection" }, ]; const Gallery = () => { return ( <section className="py-12 bg-white overflow-hidden"><div className="site-container mb-12">
        <div className="flex flex-col md:flex-row md:items-end md:justify-between w-full gap-4 md:gap-8 border-b border-transparent">
          <div>
            <h2 className="text-section text-xs mb-4 block text-2xl md:text-3xl text-neutral-900">Works</h2>
            <h3 className="text-card text-[#0f172a] text-base md:text-base lg:text-lg text-neutral-900">Technical Interior <span className="italic font-light">Execution</span></h3>
          </div>
        </div>
      </div><div className="relative flex overflow-hidden"><motion.div animate={{ x: ["0%","-50%"] }} transition={{ duration: 30, repeat: Infinity, ease:"linear" }} className="flex gap-6 whitespace-nowrap"> {[...galleryImages, ...galleryImages].map((img, idx) => ( <div key={idx} className="relative h-80 w-[450px] rounded-[2rem] overflow-hidden group shrink-0 shadow-lg"><img loading="lazy" decoding="async" src={img.url} alt={img.title} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-[#0f172a]/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity p-8 flex flex-col justify-end"><p className="text-white font-normal text-xl">{img.title}</p></div></div> ))} </motion.div></div></section> ); }; export default Gallery; 
