// @crafted-by: Sahil Sheikh | IG: @sahil_sheikh78 | Unauthorized use prohibited
"use client"; import { motion } from"framer-motion"; import Image from "next/image"; const galleryImages = [ { url:"/assets/work/filter-grid/apps-for-bharat.png", title:"Luxury Living" }, { url:"/assets/work/filter-grid/qpiai.png", title:"Healing Spaces" }, { url:"/images/Services-card/hotel.webp", title:"Grand Lobbies" }, { url:"/assets/work/filter-grid/zluri.webp", title:"Modern Workspaces" }, { url:"/images/Services-card/residential.webp", title:"Minimalist Suites" }, { url:"/assets/work/filter-grid/juego.png", title:"Technical Perfection" }, ]; const Gallery = () => { return ( <section className="py-12 bg-white overflow-hidden"><div className="site-container mb-12">
        <div className="flex flex-col md:flex-row md:items-end md:justify-between w-full gap-4 md:gap-8 border-b border-transparent">
          <div>
            <h2 className="text-section mb-4 block text-h2 text-neutral-900">Works</h2>
            <h3 className="text-card text-[#0f172a] text-h3 text-neutral-900">Technical Interior <span className="italic font-light">Execution</span></h3>
          </div>
        </div>
      </div><div className="relative flex overflow-hidden"><motion.div animate={{ x: ["0%","-50%"] }} transition={{ duration: 30, repeat: Infinity, ease:"linear" }} className="flex gap-6 whitespace-nowrap"> {[...galleryImages, ...galleryImages].map((img, idx) => ( <div key={idx} className="relative h-80 w-[450px] rounded-[2rem] overflow-hidden group shrink-0 shadow-lg"><Image fill src={img.url} alt={img.title} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-[#0f172a]/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity p-8 flex flex-col justify-end"><p className="text-white font-normal text-body-lg">{img.title}</p></div></div> ))} </motion.div></div></section> ); }; export default Gallery; 
